apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app:  server
    spec:
      containers:
      - name:  server
        image:  jayesh/app1
        ports:
        - containerPort: 8085
        env:
          - name:  SPRING_DATASOURCE_USERNAME
            value: team3
          - name:  SPRING_DATASOURCE_PASSWORD
            value: team3
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://10.97.234.202:5432/postgres
