apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image:  postgres
        ports:
        - containerPort: 5432
        env:
          - name:  POSTGRES_USER
            value: team3
          - name: POSTGRES_PASSWORD
            value: team3
